name: yolov4-gpu

dependencies:
  - python==3.8
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.4.0
    - opencv-python==4.1.2.30
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
